# docker-compose.yml
version: "3.7"
services:
  webclient:
    build: .
    ports:
      - $PORT:$PORT
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - FLASK_APP=public/main.py
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:vrqLs08CazD0j6l8@35.194.8.164:5432
    tty: true
